### ISSUE TITLE
[Testing Party] Discover People Page

### ISSUE THREAD

**Issue by zhujiumu** [gcivil-nyu-org/INET-Wednesday-Spring2023-Team-1#186]
Hi Team, just wanted to say beautiful work! The frontend and features look fantastic! I was going through the test document and I noticed something that may not be as intended:

For your reference, I was looking at this feature: 
￼
<img width="922" alt="Pasted Graphic 1" src="https://user-images.githubusercontent.com/46012088/232350710-80a00f3a-c0bb-4322-9246-8eaa3a55c7e1.png">

So I logged into your website as user1
url: http://nyubeatbuddies.com/account/login
Username: user1
Password: @1234567

I clicked on discover people at the bottom.
I got recommended a dummy user and I selected match. 
The website then recommended another user, however this time the user recommended to me was the same user I logged in as
Screenshot: 

<img width="1728" alt="Pasted Graphic" src="https://user-images.githubusercontent.com/46012088/232350718-c0d0e583-12cd-4d0b-96d6-efe9b429894c.png">

at this point, match and un-match button seems to be disabled. 

I believe after being recommended an user I should proceed to see more recommendations? If this is a feature not yet ready then kindly ignore - I might have missed it in the document.

**Comment by jakesway99** [comment]
This means the user is out of users to match with and is the expected functionality, but we'll add a pop-up to make it more clear to users that they are out of users to match with.

**Comment by jakesway99** [comment]
We have added a pop up that shows if you are out of matches and allows you to go back to the profile page.

![image](https://user-images.githubusercontent.com/103974115/234405841-540eb27a-b508-4cd5-8c59-c71b1b4b8fe2.png)
