### ISSUE TITLE
[Testing Party] Discover Events

### ISSUE THREAD

**Issue by xiaolin-zhong** [gcivil-nyu-org/INET-Wednesday-Spring2023-Team-1#189]
User  1
Username: user1
Password: @1234567

Not a bug per say, but I can see this being a pain point for a user. In the discover event page, selecting interested or going button does a full page refresh, which will only show the recent 6 events. With the user 1 account, I selected going to an event that is on May 5th, which took about ~30 'Load More' clicks. If the user decides they no longer want to go, they'd have to look for the event again by clicking on 'Load More' 30 times to find the event again to undo the going button.

![T1P2.PNG](https://images.zenhubusercontent.com/63e66002642c9855f7b4865c/4838623c-78f0-4d5d-9fc6-2d7b08f9f89b)

**Comment by jakesway99** [comment]
We are currently adding the interested/going events directly to the discover events page so the user can quickly remove them. They can also go to their profile and remove the events that way.

**Comment by jakesway99** [comment]
the user can now see interested/going events directly from the discover events page, this will be included in the next sprint demo.
