### ISSUE TITLE
[Testing Party] URLs

### ISSUE THREAD

**Issue by xiaolin-zhong** [gcivil-nyu-org/INET-Wednesday-Spring2023-Team-1#190]
As a signed in user, going to http://nyubeatbuddies.com/ redirects to a sign in page, though it didn't sign me out. Rather than (maybe) redirecting to http://nyubeatbuddies.com/application/profile. 

If I am not logged in, http://nyubeatbuddies.com/account/profile redirects to 404 rather than a log in page.

I am able to access this page without doing any password resets: http://nyubeatbuddies.com/account/password_reset/done/

I was able to access this page: http://nyubeatbuddies.com/password_reset/
I wasn't able to see if I can do anything in this page without an email to test but might leave the site vulnerable.
![image.png](https://images.zenhubusercontent.com/63e66002642c9855f7b4865c/bc105b7a-e47a-47a0-82bb-b7aa87e298ed)

**Comment by jakesway99** [comment]
fixing:

- [ ] Going to nyubeatbuddies.com should redirect to profile if you are logged in 

- [ ] The password reset page shouldn’t be hit unless user is logged in
