### ISSUE TITLE
As a typical NYUBeatBuddies user I want to be able to view my user profile that shows my music tastes and interest so that I can connect with people who have similar music interests and tastes

### ISSUE THREAD

**Issue by nikoaganev** [gcivil-nyu-org/INET-Wednesday-Spring2023-Team-1#2]

**Comment by jakesway99** [comment]
- [ ] Use static images to create top artists/songs/albums graphic 
- [ ] Replace static images with images retrieved using "Get Artist" in the spotify web api

**Comment by jakesway99** [comment]
- [ ] Use static images to create top artists/songs/albums graphic 
- [ ] Replace static images with images retrieved using "Get Artist" in the spotify web api

**Comment by jakesway99** [comment]
- [ ] Use static images to create top artists/songs/albums graphic 
- [ ] Replace static images with images retrieved using "Get Artist" in the spotify web api
